<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{c85ca7f7-62e4-4195-a50a-ed021ea2dff4}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	sStringList: ARRAY[1..5] OF STRING:=['Home','A','B','C','D'];
	Lamp: BOOL;
	stop:BOOL;
	Lamp_emergency: BOOL;
	Reset_Button: BOOL;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[Command_Control();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="8" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>